---
title: "2021-03-21-Town-Council"
description: |
  Watch your street
author:
  - name: David McGaughey
    url: {}
date: 03-25-2022
output:
  distill::distill_article:
    self_contained: false
---

# 2021 03 21 Town Council Meeting 

## Mayors notes:

$125k highway bill grant is likely to be given to UP

  - courtesy of the state of MD 
  - the money is intended to replace/repair the [famous town creek bridge(s)](https://davemcg.com/ward5/notes/2021-05-19-wheresthebridge/)
  - Given previous estimates, this is a very helpful amount of but I do not expect it to cover installing both bridges
  - So we will have to see what an engineer says about the install cost
  
$225k tot lot upgrade is in the Governer’s budget and is *likely* to be passed 

The Mayor gave permission to DeMatha to use Town Tennis Courts between 3:30-5:30 M-Th

  - March 28th - May 5
    
New Veoride contract nearly done! Mayor and Mr. Beall have been working to identify new sites. “Forced parking” the new system. So all the scooters are supposed to be left within a designated parking zone.

  - The Mayor and Mr. Beall identified 23 potential sites
  - It will be narrowed down to 10 spots
  - The final list will be brought to the council for approval
  
## PG County Councilmember Glaros is presenting next council meeting (2021-04-04)

  - She will be discussing sediment control and storm water control
  - Martha Wells hoping she will discuss traffic issues (EW Highway / Adelphi pedestrian crossing with highly ignored no-turn-on-red)
  - Adelphi road sector plan may be discussed as to how it relates to pedestrian access, road design, and traffic control?
  
## CM Ward 7 Roland Stephens proposed stipend for town council members - $1800/year? 

  - Mayor: needs to be an ordinance. No current council member could receive benefit until being (re)elected
    - 4/4 meeting bring it up for notice (not adoption)
  - I think I am against this - I don't see the point of doing this unless it helps attract more candidates to run for the position.
   
## Biermann
  - No Mow April/May? - the UP Code Enforcement Officer has been alerted to not hand out citations for overgrown yards (unless they appear to be due to neglect)
  - 4/23 Town Stream Cleanup
  - 6/25 Meadow Day, 10am-12pm. Native plants available to residents. Presentations / booths from various groups (Anacostia Watershed, Beekeeper, Tree Committee)
 

## Chief 
  - 5 incidents
  - Ward 1, 3/1 women parked in car. Resident approached car. She ran, assaulted different resident, and arrested by UP Police. Chief reminds us all to please not get confrontational - the police are trained at handling these situations. 
  - Ward 3, 3/16, Balt. Ave victim of money order fraud
  - Ward 5, 3/4. Suspicious vehicle reported. 6900 block of Pineway. Turns out be a stolen vehicle.
  - Ward 7, 3/11 6800 Wells - unoccupied vehicle on crates. Resident said it had wheels the night before.
  - Ward 7, 3/22 4000 Underwood, resident robbed at gunpoint of backpack by four people at her door. 
    - More patrols in Ward 6/7 in response
  - doing loud car stops
  - Traffic detail coming up 
  - 2/10 NCIC audit passed
  - 5/6 movie night in the park
  - **Please contact police if you see a suspicious vehicle. Police will do a welfare check.**
    - non-emergency number: **301-352-1200** <- this is a PG County Number. The chief asks you use this at this is linked into a call tracking system. Asks for calls about illegally parked or strange vehicles. 
  - Speed camera going live soon - perhaps this week? One month post going up, will go “live”
  

## Public Works Director Beall

  - 5/6 pickle ball demonstration (same as Movie Night)
  - The county continues to slowly move on giving out permits for Phase 2B
    - Mr. Beall is hoping to get the permit in April
  - The town is using Soltesz for estimation of PG County stormwater acceptance project (bring up storm water system elements up to date)
    - once we have estimation of design and construction costs, then we can submit to county for MOU whereby the county would reimburse the town for expenses
    - the under-sized storm water system underneath Claggett-Pineway (and running between a few houses on Pineway) is the primary concern of this work. Also looking into adding inlet at Claggett-Pineway/Woodberry (would depend on engineer’s opinion of the usefulness of it)

