---
title: "Town Council 2021-11-15"
description: |
  New town clerk appointed
author:
  - name: David McGaughey
    url: {}
date: 11-15-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Washington Gas
Approved MOU. They will soon tear up a stretch of Van Buren to do some gas work

# DOC 

Discussing "Garden Apartments" in PG Plaza Mall area

Discuss new sector plan for Purple Line / our region

# Recycling

Interest in polystyrene recycling at the town level to be discussed 

Sustainability Committee exploring the issue (see more below from Mickey)

# Tree and Rules Committee
Working on on Leaf blower ordinance implementation language. Tree ordinance being worked on. 

# Fiscal Meeting
Auditor says town finances are in good shape 

# LEGISLATIVE RESOLUTION 21-O-07
24 hour monitoring of Baltimore and EW Highway (these are MD state controlled) will be possible now. 

Adelphi is not possible, as that is under PG County control. Chief Baker is working on getting permission
for 24 hour monitoring of Adelphi. 

Goal is, again, to slow down traffic on these roads to reduce noise pollution and enhance safety.

# New Town Clerk
Our existing Town Clerk, Andrea Markavitch, has moved to Connecticut. The town has hired a new Clerk, TC Hegeman (so she *could* be addressed as TC TC Hegeman). She is the current clerk of Cheverly, MD. She was interviewed by the Mayor, Town Administrator Deutsch, and Andrea. 30 interviews were submitted. Four were interviewed. TC Hegeman was the unanimous choice of all three.

TC Hegeman will begin her job next week. Andrea will be gently transitioning out of her position, so she can assist the incoming Town Clerk. 

# Chief Baker

November 2nd: UPES. Rock tossed through window. No video footage.  

Two similar incidents of busted windows at the bus shelters in the region

One officer is a notary.

# Treasurer Baden
$24,500 in red light camera revenue for October. Will increase. Then decrease as speeds decrease and people get used to the camera. Money can only be spent on public safety. 

# Public Works Director Beall
Ward 6 getting sidewalk repairs. Xmas lights to be installed this week. Blankets on town field. Fountain off at town playground. Ward 2 next for leaf pickup. Planting trees in town. 

EPS (Polystyrene). Talked with vendor in Crofton. Multiple Public Works director on the call. Logistical issues. Most crucial is that not much more capacity to collect (at a town amount of quantity). Mickey suggested perhaps adding the EPS collection during the periodic town collection dates (with the paper shredding / electronics recycling). 

Phase 2B. Waiting for permit approval from county. Expecting it in early December, which would be good as the town's "rate" for the work will get more expensive starting Jan 1, 2022. 

# NOT COUNCIL: Beall Run In

Was chatting with Mickey and asked him about something that had confused me. The council has approved several drain connections underneath sidewalks. I was confused who was requesting these and who was paying for them. Apparently when the town replaces sidewalks, they ask whether the homeowner wants an existing drainage (sump / etc) pipe that exits onto/near the sidewalk routed underneath the sidewalk and exiting onto the road. The town is paying for these. Which costs (ballpark) around $300. This is two fold:

1. Everyone hates having drainage onto the sidewalks, which freezes in the winter and thus makes the sidewalks hazardous
2. It was very hard to get a homeowner to agree, on very short notice, whether to pay for the piping.

So, if you see white lines being drawn on your sidewalk and know of some pipes that could benefit from being routed onto the road, please contact Mickey immediately. I noticed Ward 5/Pineway was marked up today. 

