---
title: "Blowers"
description: |
  Full of air
author:
  - name: David McGaughey
    url: {}
date: 06-19-2021
output:
  distill::distill_article:
    self_contained: false
preview: electric_blower.jpg
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Issue
The UP Town Council will soon (July 2021 or so) vote on whether to ban *gas-powered* leaf blowers as of January 1, 2023.

# My position
*Lean* no (as of June 19 2021)

# Some background reading
UP Policy, Rules, and Municipal Structure Committee statement: [here](https://www.upmd.org/DocumentCenter/View/1832/210207-PRMSC-Statement-on-Gas-Powered-Leaf-Blowers?bidId=)

Atlantic article on how and why DC banned gas-powered leaf blowers as of 2022: [here](https://www.theatlantic.com/magazine/archive/2019/04/james-fallows-leaf-blower-ban/583210/)

DCist update on DC residents trying to *push up* the ban date: [here](https://dcist.com/story/20/05/07/washingtonians-are-in-a-huff-about-leaf-blowers-again-pandemic-edition/)

Washington University post that briefly summarizes the air pollution impact (on all gas-powered yard equipment, not just blowers): [here](https://sustainability.wustl.edu/rethinking-lawn-equipment-2/). "A 2011 study showed that a leaf blower emits nearly 300 times the amount of air pollutants as a pickup truck. Similarly, a 2001 study showed that one hour using a gas-powered lawn mower is equivalent to driving a car 100 miles."

# The resolution
Read it [here](https://www.upmd.org/DocumentCenter/View/1833/Draft-LR-21-O-04-Amendment-of-Chapter-7-Gas-Powered-Leaf-Blowers?bidId=).

The relevant line is "BEGINNING JANUARY 1, 2023, IT SHALL BE UNLAWFUL FOR ANY OWNER OR OCCUPANT OF REAL PROPERTY LOCATED WITHIN THE TOWN, OR ANY GUEST, EMPLOYEE OR CONTRACTOR OF SUCH PERSON, TO USE A GAS- POWERED LEAF BLOWER ON THAT PROPERTY."

# Pros for banning gas powered leaf blowers:

1. Gas-powered leaf blowers emit SUBSTANTIAL air pollution. Electric does not. Pollution *is* produced by electricity creation of course, but it is from an **emissions-controlled** power plant very far away. Essentially gas-powered blowers make the air **worse for you and your neighbors, some of which suffer from respiratory issues**.
2. Gas-powered leaf blowers emit SUBSTANTIAL noise pollution. You all know. You can hear it. From my brief Googling: gas blowers (at 50 feet) emit around 80-90db (which is in the "damages your ears" range) and comparable electric blowers emit around 60-70db (which is in the "maybe annoying" range). 

# Cons for banning:

1. In the short term, it will likely drive up cost of contractor yard maintenance.
2. In the short term, contractors may *refuse* to work in UP

# My longer position
Personally, I think this should pass as written. But....I'm young (or middle-aged depending on your perspective), hand-rake my yard, and don't usually pay contractors to do yard work. I understand many people do *rely* on contractors to keep their yard maintained. Our town has a lot of trees and a lot of leaves. It needs to be *feasible* for contractors to swap over to electric for the blowers **by  2023**. This I am unsure about. 

If I could see some evidence / persuasive anecdotes that banning gas powered blowers would *moderately* (or less) drive up costs of leaf removal, then I would lean toward voting "yes." I am just concerned that switching to electric blowers is not practical in the next 18 months. My brief Googling does not find many "contractor" grade blowers. 

# What should I do as a neighbor and a member of a community right now?
Ask your contractor **right now** to reduce (or even stop) the amount of blowing done in your yard. It seems like the "default" position of yard contractors is to spend 10+ minutes walking around blowing grass clippings around year-round. This *is not necessary* (unless the aesthetics are very important to you). If you have read this far you *now know* that blowing makes the air quality worse for you *and your neighbors*. 

Furthermore you can consider trying to switch to an "all electric" yard service company. Chevy Chase has made a [list](https://www.townofchevychase.org/431/Quiet-and-Clean-Landscapers) (I don't know whether any of them service UP though.....). Gas-powered lawn mowers also use the same high pollution engine design. 

We wore masks to make ourselves and our neighbors safer. We can make a similar gesture by reducing our gas yard tool usage. 

# I DISAGREE, YOU MONSTER

Well, email or call to me to let me know your opinion. I will say, as of today (June 19 2021), I have had approximately five "DO NOT PASS THIS" emails, one "I can deal with whatever the outcome", and one "PLEASE PASS THIS" emails. And a whole bunch of informal "I don't really care; this is boring me" conversations with random people.


