---
title: "Town Council 2021-09-07 "
description: |
  Relatively Quiet
author:
  - name: David McGaughey
    url: {}
date: 09-22-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


First a few notes from the Public Facilities Committee meeting on September 16th (**not the town council meeting**).

- David Deutsch attended
- We had three asks, in order of importance:

    1. Price out a pre-fabricated shed (approximately 25 x 30 feet)
        - consult with Public Works Director Mickey Beall
        - purpose is for dry storage of commonly used items, to free up space in the existing town hall and town garage and to reduce employee travel time spent going back and forth 
        - select location that would not interfere with **potential** town hall expansion
        - run power to the shed for lights, security cameras, power outlets
    2. Look into feasibility of temporary housing / unit (roughly similar to temporary classrooms modular units)
        - purpose would be threefold: 
      - 1. small meeting space for council / residents
      - 2. common area space for public works / police. In hot and cold weather the fairly sizeable number of staff are sharing a very cozy kitchen.
      - 3. Idea would be to "demo" the usefulness of an addition on town hall for a much more modest sum of money
    3. Car charger(s) at town hall
        - prepping for future purchases, which are more and more likely to be electric
  
# Town Council Meeting 

## Award for esteemed Ward 5 resident John Tabori
Former Mayor and Ward 5 CM John Tabori was given a (surprise) commendation by PG County Councilmember Dannielle Glaros for his long service to the region in serving on county-level development committees. 

John also gave a brief presentation on the formation of the UP Development Overview Committee, which is still *very* relevant today as this committee is responsible for recommendation a course of action regarding the Western Gateway / Guilford Woods project.

If you see John, congratulate him! Without him, we'd likely have no DOC and thus a much smaller voice in the discussion around the development surrounding us. 

## Art in the Park
Inaugural "Art in the Park" will happen this Saturday (9/25) from 1-4 PM in the town playing field. 17 (?) artists will be presenting.

## Speed camera
Went "live" on 9/13. Generated over 100 tickets in the first two days. Starting 10/1 we will have the option of running the camera 24/7.

## Phase 2B
Still no start date for the Phase 2B street renovation (which includes new sidewalks on Clagett-Pineway) as Mickey is still working on the permitting.


